### ISSUE TITLE
ie 11 error

### ISSUE THREAD

**Issue by bjseong** [wonism/react-kakao-login#14]
만들어 주신 라이브러리 잘 쓰고 있는데요
ie11에서 에러가 나서 문의 드립니다.

import 'core-js/stable';
import 'regenerator-runtime/runtime';
import 'react-app-polyfill/ie9';
import 'react-app-polyfill/stable';

index.js에 다 추가한 상태고

<KaKaoLogin
                                    jsKey={'******'}
                                    onSuccess={responseKaKao}
                                    onFailure={responseKaKaoFail}
                                    getProfile={true}
                                    className="login_kakao">
                                        카카오톡으로 로그인
                                </KaKaoLogin>
했습니다.

그런데

ie11에서
SCRIPT438: 개체가 'append' 속성이나 메서드를 지원하지 않습니다.

이런 오류가 납니다.
좋은 방법 없을 까요?

**Comment by wonism** [comment]
https://caniuse.com/mdn-api_parentnode_append

appendChild 로 수정하였습니다.
1.2.3 버전 사용하시면 해결될 거예요

**Comment by FrancisSeong** [comment]
에러 안나고 ie 실행 됩니다. 감사합니다.
