### ISSUE TITLE
권한팝업 그냥 닫으면 fail 콜백이 안오네요

### ISSUE THREAD

**Issue by ghost** [wonism/react-kakao-login#15]
로그인창 뜨고 로그인 한 후에 권한요청 팝업을 닫으면 window_closed 오류로 에러 콜백이 와야 하는걸로 아는데,
해당 콜백이 오질 않네요 ㅠ

**Comment by wonism** [comment]
확인이 늦어 죄송합니다.

카카오 계정 로그인 페이지가 뜬 상태에서 해당 창을 닫았을 때,
에러가 발생해야하는데 에러가 발생하지 않는다는 말씀이신 것인가요?

https://developers.kakao.com/tool/demo/login/login
카카오 개발자 사이트의 예제에서도 위 스텝 진행할 시, fail 함수가 실행이 안 되는 것으로 보이네요.
```
    Kakao.Auth.login({
      fail: function(err) {
        alert(JSON.stringify(err))
      },
    })
```
