### ISSUE TITLE
사용방법이 바뀌었는데 업데이트가 안되어서 불편합니다.

### ISSUE THREAD

**Issue by tmmoond8** [wonism/react-kakao-login#16]
현재 사용방법을 보는 곳은 github 의 소스 코드 아닌 곳에는 가이드가 되어 있지 않네요.
이전에 사용한 것이 변경되었는데 확인할 곳이 없습니다.
storybook 애드온에 스토리에 작성된 코드 보는 것이 있는데 추가 되면 도움이 될 것 같습니다.

**Comment by wonism** [comment]
애드온 추가하였습니다 🙏🏼
