### ISSUE TITLE
kakao logout

### ISSUE THREAD

**Issue by timo-kang** [wonism/react-kakao-login#19]
로그인 시 로그아웃이 정상적으로 되지 않습니다..

로그인 시 항상 다른 계정 로그인을 요청한다면
```
window.Kakao?.Auth.login( {
    ...,
    reauthenticate: true
} )
```
위와 같이 reauthenticate를 추가해도 좋을 것 같습니다.

많은 사람들이 이 모듈을 많이 사용하면 좋겠네요.

**Comment by timo-kang** [comment]
@wonism

**Comment by wonism** [comment]
@kingworm 
https://developers.kakao.com/sdk/reference/js/release/Kakao.Auth.html#.login__anchor
에 보시면 `reauthenticate` 같은 옵션은 없더라구요.

대신,
`login` 말고 `loginForm` 을 사용하면
로그인 버튼 클릭 시, 카카오톡 로그인을 하는 페이지가 뜨는데 이를 사용하도록 했습니다.
`useLoginForm` 값을 `true` 로 주시면 `loginForm` 을 사용하게 됩니다.
