### ISSUE TITLE
package name 중복 에러

### ISSUE THREAD

**Issue by sangkeun-park** [wonism/react-kakao-login#2]
**npm i -S react react-dom react-kakao-login** 를 실행하면 아래와 같은 오류가 발생합니다.

> npm i -S react react-dom react-kakao-login
> npm ERR! code ENOSELF
> npm ERR! Refusing to install package with name "react-kakao-login" under a package
> npm ERR! also called "react-kakao-login". Did you name your project the same
> npm ERR! as the dependency you're installing?
> npm ERR!
> npm ERR! For more information, see:
> npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\SKPARK\AppData\Roaming\npm-cache\_logs\2017-10-09T12_24_55_900Z-> debug.log

저는 **package.json**의 **name:react-kakao-login**을 일단 **react-kakao-login-test** 로 바꿔서 문제를 해결하기는 했는데, 소스 차원에서 미리 수정이 필요해보입니다.

**Comment by wonism** [comment]
NPM 패키지 이름(`npm init` 으로 패키지 이름을 설정하지 않은 경우, 현재 경로)이 `A`라고 할 경우,
디펜던시에 `A`라는 의존성이 있으면 해당 패키지 `A`는 설치되지 않습니다.
사용법을 애매하게(?) 적어뒀던 것 같네요.
`README.md` 업데이트해뒀습니다!

---
사용해주셔서 감사합니다 :)
