### ISSUE TITLE
KakaoAccount.gender

### ISSUE THREAD

**Issue by nobel6018** [wonism/react-kakao-login#20]
src > types.ts

interface KakaoAccount {
  /** 프로필 정보 */
  profile: Profile;
  /** 대표 이메일 */
  email: string;
  /** 연령대 ref: https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info */
  age_range: string;
  /** 생일, MMDD 형식 */
  birthday: string;
  /** 태어난 해, YYYY 형식 */
  birthyear: string;
  /** 성별, femail/mail */
  gender: "femail" | "mail";
  /** 전화번호. 카카오톡에 등록된 전화번호 */
  phone_number: string;
  /** 연계정보. 암호화된 이용자 확인 값 */
  ci: string;
}

gender가 male, female 인데 오타인거 같습니다

**Comment by wonism** [comment]
감사합니다 🙇🏼
