### ISSUE TITLE
npm 또는 yarn으로 설치시 src폴더와 demo폴더가 다운로드되지 않습니다.

### ISSUE THREAD

**Issue by gitpushyj** [wonism/react-kakao-login#6]
src폴더와 demo폴더를 제외한 파일들은 다운로드가 되는데 두 폴더는 내려받아지질 않네요.
제가 어딘가 설치를 잘못할 걸까요? 아니면 라이브러리에 오류가 있는걸까요?

**Comment by wonism** [comment]
패키지에서 개발용 소스들에 접근할 필요가 없다고 생각해서 `.npmignore`를 수정했어요.
(https://github.com/tj/node-prune 같은 툴이 있긴 하지만요)

마찬가지로, 웹팩으로 번들링된 파일이 존재하는 `dist` 디렉토리도 `.gitignore`에 포함되었습니다.

**Comment by gitpushyj** [comment]
src 폴더가  없으면 사용할 수 없는 것 아닌가요?

**Comment by wonism** [comment]
헉.. 배포 전에 돌리는 스크립트를 잘못 짰네요
죄송합니다 ㅠㅠ
`src`는 아니고, `dist`가 있어야 사용할 수 있어요.
~지금 수정중이에요.~

1.0.10 버전 unpublish 하고
1.0.11 버전 publish 했습니다.

https://www.npmjs.com/package/react-kakao-login
