### ISSUE TITLE
typescript import error

### ISSUE THREAD

**Issue by tjholic** [wonism/react-kakao-login#9]
![image](https://user-images.githubusercontent.com/6178603/76285192-7ac3ba80-62e2-11ea-9d36-4ce0e2464500.png)

(2,26):Import declarations in a namespace cannot reference a module. 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/6178603/76285113-48b25880-62e2-11ea-82af-9f1a515e4731.png)

import * as KakaoLogin from 'react-kakao-login'; 로 했는데도 동일하게 발생 됩니다.

확인 부탁드립니다.
실제로 react module은 project에서 설치 되어 있습니다.

**Comment by wonism** [comment]
혹시 `1.2.2` 로 업데이트 해보시겠어요?
그래도 안 되면 간단한 프로젝트 세팅이라도 보여주시면 좋을 것 같습니다
